mutation($todoId: ID) {
    toggleTodo(todoId: $todoId) {
        ...TodoContents
    }
}

fragment TodoContents on TodoNode {
    id
    title
    text
    done
    createdDate
    dueDate
    category {
        id
        name
    }
}
